#start cloudbuild

steps:

#build container image
- id: 'Build App'
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      echo ""
      echo "=============Building Docker image=============="
      echo "========== At project: ${PROJECT_ID} ==========="
      echo "================================================"
      docker build -t europe-west1-docker.pkg.dev/$PROJECT_ID/altostratus-42-reto-go:$COMMIT_SHA .
      docker push europe-west1-docker.pkg.dev/$PROJECT_ID/altostratus-42-reto-go:$COMMIT_SHA

#deploy container image
- id: 'Deploy Cloud Run'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      echo ""
      echo "=============Deploying Docker image=============="
      echo "========== At project: ${PROJECT_ID} ==========="
      echo "================================================"
      gcloud run deploy altostratus-42-reto-go --image=europe-west1-docker.pkg.dev/$PROJECT_ID/altostratus-42-reto-go:$COMMIT_SHA --platform=managed --region=europe-west1 --allow-unauthenticated --quiet

#deploy container image
- id: 'Deploy Cloud Run'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      echo ""
      echo "=============Deploying Cloud Run=============="
      echo "========== At project: ${PROJECT_ID} ==========="
      echo "================================================"
      echo ""

      gcloud run deploy altostratus-42-reto-go \
      --image=europe-west1-docker.pkg.dev/$PROJECT_ID/altostratus-42-reto-go:$COMMIT_SHA \
      --region=europe-west1 \
      --platform=managed \
      --port=8080 \
      --set-env-vars "ENV=dev" \
      --set-env-vars "MONGOURI=mongodb+srv://psimarro:psimarro@cluster0.5gdqytz.mongodb.net/?retryWrites=true&w=majority&appName=psimarro"
      --project=gke-alt-test

#[END cloudbuild]